sudo: false
language: python
python:
  - "2.7"
branches:
  only:
    - master
    - develop
install:
  - make reqs
script:
  - make pep8
  - make flake8
  - make test
  - make coverage
after_success:
  - coveralls
